const TASK_TEMPLATES = {
  'PR': [
    'Confirm campaign objectives and key messages',
    'Identify media angles',
    'Confirm spokespeople and proof points',
    'Draft press release or media alert',
    'Develop media pitch copy',
    'Prepare media kit (imagery, logos, boilerplate, fact sheet, bio)',
    'Build targeted media list',
    'Pitch priority journalists',
    'Send wider pitch release',
    'Conduct follow-ups',
    'Manage media enquiries and interview requests',
    'Track all coverage',
    'Compile reporting summary',
  ],
  'PR Light': [
    'Confirm PR angle and key messages',
    'Define realistic media targets',
    'Draft short release or pitch note',
    'Prepare supporting assets',
    'Build focused media contact list',
    'Internal review of pitch materials',
    'Client approval',
    'Pitch selected journalists',
    'Follow-up round',
    'Track coverage',
    'Short wrap-up report',
  ],
  'Content - Social': [
    'Confirm platforms, content pillars and posting cadence',
    'Audit existing social channels',
    'Gather client inputs and upcoming milestones',
    'Create content calendar',
    'Draft captions',
    'Brief design and visuals',
    'Internal review',
    'Client approval',
    'Schedule content',
    'Check live posts after publishing',
    'Monitor comments and DMs',
    'Monthly performance report',
  ],
  'Content - eDM': [
    'Confirm audience segment, objective and CTA',
    'Define send purpose and schedule',
    'Confirm database and send platform access',
    'Draft subject line options',
    'Write email body copy',
    'Design and format eDM',
    'Add UTM tracking and links',
    'Internal review and test send',
    'Client approval',
    'Final link check and send',
    'Performance report',
  ],
  'Content - Web/Blogs/Other Copy': [
    'Confirm content type and brief',
    'Define audience, objective and key message',
    'Research source materials',
    'Draft headline, intro and body copy',
    'Internal edit',
    'Account Manager review',
    'Client review',
    'Final proof',
    'Prepare upload-ready copy with metadata',
    'Confirm publishing responsibility',
    'Track performance',
  ],
  'Content - Influencer': [
    'Confirm campaign objective and creator profile',
    'Confirm budget and gifted or paid model',
    'Research and build influencer longlist',
    'Prepare shortlist for client approval',
    'Create influencer brief',
    'Outreach to creators',
    'Negotiate rates and confirm agreements',
    'Manage logistics',
    'Share brief and track content deadlines',
    'Review draft content',
    'Monitor live posts and capture links',
    'Campaign report',
  ],
  'Content - Shortform Capture': [
    'Confirm shoot objective and outputs',
    'Build shot list',
    'Confirm location, talent and access',
    'Confirm shoot style',
    'Film and capture content',
    'Select best clips',
    'Edit reels, shorts and stories',
    'Add captions, music and branding',
    'Internal review',
    'Client approval',
    'Schedule or deliver final files',
    'Track performance',
  ],
  'Content - Video Production': [
    'Confirm objective, audience and video format',
    'Develop creative concept',
    'Write script or talking points',
    'Prepare storyboard or shot list',
    'Coordinate talent and locations',
    'Book crew',
    'Shoot video',
    'First edit',
    'Client review and revisions',
    'Colour, sound and captions',
    'Export all required formats',
    'Deliver files and create cutdowns',
    'Track performance',
  ],
  'Brand Activation - Events & Partnerships': [
    'Define activation objective and success metrics',
    'Develop creative concept',
    'Create activation and event plan',
    'Build budget',
    'Source and confirm suppliers',
    'Prepare run sheet',
    'Build invite list',
    'Send invitations and track RSVPs',
    'Coordinate media and influencer attendance',
    'Manage event day delivery',
    'Post-event follow-up and thank yous',
    'Post-event report',
  ],
  'Awards': [
    'Research relevant award opportunities',
    'Assess likelihood of success',
    'Recommend awards calendar',
    'Confirm project or brand being submitted',
    'Gather required information and evidence',
    'Map evidence against judging criteria',
    'Draft award submission',
    'Internal proof',
    'Client approval',
    'Upload entry and confirm payment',
    'Prepare amplification plan if shortlisted or won',
  ],
  'Paid Media': [
    'Confirm objective, audience and channels',
    'Confirm budget, campaign dates and KPIs',
    'Write ad copy variations',
    'Brief design and video assets',
    'Confirm ad account access',
    'Install tracking pixels and UTMs',
    'Build campaigns and ad sets',
    'Internal review',
    'Client approval',
    'Launch campaign',
    'Monitor and optimise performance',
    'Paid media report',
  ],
  'Design': [
    'Confirm asset purpose, format and platform',
    'Gather brand guidelines and references',
    'Define required outputs and dimensions',
    'Create first draft',
    'Internal review',
    'Client review',
    'Revisions',
    'Export final files',
    'Save and organise in shared folder',
  ],
};

module.exports = { TASK_TEMPLATES };
